global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flask_server_1'
    static_configs:
      - targets: ['app:6200']

  - job_name: 'flask_server_2'
    static_configs:
      - targets: ['app:6201']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
